[package]
name = "localserver"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mio = { version = "1.0", features = ["os-poll", "net", "os-ext"] }
