servers:
  - host: "127.0.0.1"
    server_name: "myserver.com"
    max_body_size: 1048576
    port: 9090
    root: "./www/site2"
    methods: [GET]

    error_pages:
      400: "/www/errors/400.html"
      404: "/www/errors/404.html"
      405: "/www/errors/405.html"
      413: "/www/errors/413.html"
      500: "/www/errors/500.html"

    routes:
      - path: "/"
        root: "./www/html"
        methods: ["GET"]
        index: "index.html"

      - path: "/upload"
        root: "./www"
        methods: ["GET", "POST"]
        upload_dir: "./www/uploads"

      - path: "/old-site"
        redirect: "/new-site"

      - path: "/scripts"
        root: "./www/scripts/"
        methods: ["GET"]
        cgi_interpreter: /usr/bin/python3
        cgi_extension: ".py"

      - path: "/scripts/sh"
        root: "./www/scripts/"
        methods: ["GET"]
        cgi_interpreter: /usr/bin/sh
        cgi_extension: ".sh"

max_server_size: 10485760
timeout_seconds: 30
